dividendslist <- c("Dividends (cents)")
sharesOutstandinglist <- c("Shares Outstanding (m)")
revenuelist <- c("Revenues (m)")
incomeTaxRatelist <- c("Income tax rate (%)")
netProfitBeforeAbnormalslist <- c("Net Profit Before Abnormals (m)")
netProfitlist <- c("Net Profit (m)")
longTermDebtlist <- c("Long term debt (m)")
shareholdersEquitylist <- c("Shareholders Equity (m)")
EBITDAlist <- c("EBITDA (m)")
EBITlist <- c("EBIT (m)")