---
title: "Webscraping Commsec"
author: "KevinHo"
date: "15 February 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## About

This is my first exercise in webscraping
I'm following the tutorial listed [here](https://blog.rstudio.org/2014/11/24/rvest-easy-web-scraping-with-r/).
And the CRAN repository is [here](https://cran.r-project.org/web/packages/rvest/index.html)

## Setup



yahoo finance time series

```{r}
#######################################################################
##Alternate method to download all key stats using XML and x_path – PREFERRED WAY
#######################################################################


require(XML)
require(plyr)
getKeyStats_xpath <- function(symbol) {
  yahoo.URL <- "http://finance.yahoo.com/q/ks?s="
  html_text <- htmlParse(paste(yahoo.URL, symbol, sep = ""), encoding="UTF-8")

  #search for <td> nodes anywhere that have class ‘yfnc_tablehead1’
  nodes <- getNodeSet(html_text, "/*//td[@class='yfnc_tablehtthead1']")
  
  if(length(nodes) > 0 ) {
   measures <- sapply(nodes, xmlValue)
   
   #Clean up the column name
   measures <- gsub(" *[0-9]*:", "", gsub(" \\(.*?\\)[0-9]*:","", measures))   
   
   #Remove dups
   dups <- which(duplicated(measures))
   #print(dups) 
   for(i in 1:length(dups)) 
     measures[dups[i]] = paste(measures[dups[i]], i, sep=" ")
   
   #use siblings function to get value
   values <- sapply(nodes, function(x)  xmlValue(getSibling(x)))
   
   df <- data.frame(t(values))
   colnames(df) <- measures
   return(df)
  }
}

tickers <- c("AAPL")
stats <- ldply(tickers, getKeyStats_xpath)
rownames(stats) <- tickers
write.csv(t(stats), "FinancialStats_updated.csv",row.names=TRUE)  
```




Lets try Rselenium without docker. Help from StackO - RESOLVED MOTHER FUCKER!

EDIT: I've now removed all instances of my username and password. Time to get to work

```{r}

#Install firefox
#Download geckodriver and unzip the exe here c:\bin\geckodriver
#Run the following in cmd >set PATH=%PATH%;C:\bin\geckodriver
#start Selenium server by opening a command prompt and then type
#cd ~YOUR_R_PATH~\library\RSelenium\bin
#Download selenium server into the above location http://www.seleniumhq.org/download/ 
#java -jar selenium-server-standalone-x.xx.x.jar
library(RSelenium)

remDr <- remoteDriver()
remDr$open()

remDr$navigate("https://www2.commsec.com.au/Public/HomePage/Login.aspx")


# send password and Enter - deprecated
# passwd <- remDr$findElement(using = "id", value = "ctl00_cpContent_fakepassword")
# passwd$clearElement()
# passwd$sendKeysToElement(list(aPhrase, "\uE007"))
```

The following script is used once you've logged in.
```{r}
#ONCE LOGGED IN
#navigate to a financials page for a stock
#send stock search
source("helpers.R")
library(XML)
library(stringi)
library(dplyr)

sleepytime <- 5

conn <- file("data/20170201-all-ords.csv","r")
allords <- read.csv(conn, header = TRUE, skip = 1 )
close(conn)

for(stockcode in allords[[1]]){
    stock <- remDr$findElement(using = "id", value ="ctl00_BodyPlaceHolder_FinancialsView1_ucCompanyProfilesHeader_ucSecuritySearch_txtSmartSearch_Input")
    stock$clearElement()
    stock$sendKeysToElement(list(stockcode))
    Sys.sleep(sleepytime)
    stock$sendKeysToElement(list("\uE007"))
    Sys.sleep(sleepytime)
    
    #Convert Page to tables
    doc <- htmlParse(remDr$getPageSource()[[1]])
    tables <- readHTMLTable(doc, header = TRUE)
    
    #clean the output
    i=1
    
    while(i < length(tables)+1) {
        names(tables[[i]]) <- stri_trim(stri_replace_all_fixed(names(tables[[i]]),"\n",""))
        
        i = i+1
    }
    
    companyHistoricals <- findCompanyHistoricals(tables)
    historicalFinancials <- findHistoricalFinancials(tables)
    balanceSheet <- findBalanceSheet(tables)
    
    #Iterate over this
    
    colnumber = 2
    rs <- record.new()
    while (colnumber <= dim(companyHistoricals)[2]) {
        a <- data.frame(
                "Company_Name" =stockcode
                 ,"Date" = names(companyHistoricals)[colnumber]
                 ,"Dividends" = ifelse(length(which(companyHistoricals[,1] %in% "Dividends (cents)")) == 0,NA, as.numeric(gsub("[^0-9\\.]","",as.character(companyHistoricals[which(companyHistoricals[,1] %in% "Dividends (cents)"),][colnumber][[1]]))))
                 ,"Shares_Outstanding" = ifelse(length(which(companyHistoricals[,1] %in% "Shares Outstanding (m)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(companyHistoricals[which(companyHistoricals[,1] %in% "Shares Outstanding (m)"),][colnumber][[1]]))))
                 ,"Revenues" = ifelse(length(which(historicalFinancials[,1] %in% "Revenues (m)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(historicalFinancials[which(historicalFinancials[,1] %in% "Revenues (m)"),][colnumber][[1]]))))
                 ,"Income_Tax_Rate" = ifelse(length(which(historicalFinancials[,1] %in% "Income tax rate (%)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(historicalFinancials[which(historicalFinancials[,1] %in% "Income tax rate (%)"),][colnumber][[1]]))))
                 ,"Net_Profit_Before_Abnormals" = ifelse(length(which(historicalFinancials[,1] %in% "Net Profit Before Abnormals (m)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(historicalFinancials[which(historicalFinancials[,1] %in% "Net Profit Before Abnormals (m)"),][colnumber][[1]]))))
                 ,"Net_Profit" = ifelse(length(which(historicalFinancials[,1] %in% "Net Profit (m)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(historicalFinancials[which(historicalFinancials[,1] %in% "Net Profit (m)"),][colnumber][[1]]))))
                 ,"Long_term_debt" = ifelse(length(which(historicalFinancials[,1] %in% "Long term debt (m)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(historicalFinancials[which(historicalFinancials[,1] %in% "Long term debt (m)"),][colnumber][[1]]))))
                 ,"Shareholders_Equity" = ifelse(length(which(historicalFinancials[,1] %in% "Shareholders Equity (m)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(historicalFinancials[which(historicalFinancials[,1] %in% "Shareholders Equity (m)"),][colnumber][[1]]))))
                 ,"EBITDA" = ifelse(length(which(historicalFinancials[,1] %in% "EBITDA (m)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(historicalFinancials[which(historicalFinancials[,1] %in% "EBITDA (m)"),][colnumber][[1]]))))
                 ,"EBIT" = ifelse(length(which(historicalFinancials[,1] %in% "EBIT (m)")) == 0, NA, as.numeric(gsub("[^0-9\\.]","",as.character(historicalFinancials[which(historicalFinancials[,1] %in% "EBIT (m)"),][colnumber][[1]]))))
                 ,"Total_Current_Assets" = NA
                 ,"Total_Current_Liabilities" = NA 
                   
        )
        rs<-rbind(rs,a)
        colnumber <- colnumber + 1
    }
    
    rsd <- tbl_df(rs)
    
    colnumber = 2
    while (colnumber <= dim(balanceSheet)[2]) {
        rsd <- mutate(rsd
                ,Total_Current_Assets = ifelse(Date== paste(names(balanceSheet)[colnumber],"/06",sep=""), as.numeric(gsub("[^0-9\\.]","",as.character(balanceSheet[which(balanceSheet[,1] %in% "Total Current Assets"),][colnumber][[1]]))),Total_Current_Assets)
               
                ,Total_Current_Liabilities = ifelse(Date== paste(names(balanceSheet)[colnumber],"/06",sep=""), as.numeric(gsub("[^0-9\\.]","",as.character(balanceSheet[which(balanceSheet[,1] %in% "Total Current Liabilities"),][colnumber][[1]]))),Total_Current_Liabilities) 
        )
        colnumber <- colnumber + 1
    }
    
    write.csv(rsd,paste("loading/",format(Sys.time(), "%y%m%d %H%M%S")," ",stockcode,".csv",sep = "") )
}

```

 
 